### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by PhilAndrew** [zhihan/minisat-scala#1]
Hi there, can I ask you a question, can Choco3 generate a SAT file to be solved by your SAT solver?
Do you know of any constraint programming library which can generate a SAT file to be solved by your SAT solver for school timetable solving?

**Comment by zhihan** [comment]
I am not really familiar with Choco3. But I think constraint solvers are more general than SAT solvers. SAT solvers are seldom used alone. They are usually embedded in SMT solvers as the boolean solver core, as far as I know.
